### ISSUE TITLE
trace_file fails with predict.R in the aster package

### ISSUE THREAD

**Issue by programLyrique** [PRL-PRG/argtracer#3] opened 2021-12-17 15:48 UTC
In the `tests` directory:

```R
> argtracer:::test_trace_file('predict.R')

*** Temp DB path:  /tmp/RtmpF84AFm/file4c8b32b603746.sxpdb 
[1] TRUE
[1] TRUE
[1] TRUE
[1] TRUE
[1] TRUE
Error in FUN(X[[i]], ...) : 
  cannot coerce type 'closure' to vector of type 'character'
> traceback()
9: lapply(list(...), as.character)
8: .makeMessage(..., domain = domain, appendLF = appendLF)
7: message("Tracing ", file, " failed: ", e$message)
6: value[[3L]](cond)
5: tryCatchOne(expr, names, parentenv, handlers[[1L]])
4: tryCatchList(expr, classes, parentenv, handlers)
3: tryCatch({
       code <- parse(file = file)
       code <- as.call(c(`{`, code))
       time <- system.time(ret <- trace_code(db, code, quote = FALSE))
       status <- ret$status
       db_size <- sxpdb::size_db(db)
   }, error = function(e) {
       message("Tracing ", file, " failed: ", e$message)
       error <<- e$message
       status <<- -1
   })
2: trace_file(file, db_path)
1: argtracer:::test_trace_file("predict.R")
```

After adding `browser` in the mix, I can see that `file` is now a closure and not a character vector anymore!

```R
Browse[1]> file
function (description = "", open = "", blocking = TRUE, encoding = getOption("encoding"),
    raw = FALSE, method = getOption("url.method", "default")) 
{
    .Internal(file(description, open, blocking, encoding, method, 
        raw))
}
```

The error carried in `e`:

```R
Browse[1]> e
<simpleError in sxpdb::size_db(db): object 'db' not found>
```
So it seems that we lose the local environment of the surrounding function: `db_path` is not defined anymore for instance (according to `exists`) ; `db` is not anymore either.

`browser()` just after the `trace_code` function also shows that `code` is not defined anymore there. However, `trace_file` ran without problems according to its status code.

```R
Browse[1]> ret
$status
[1] 0

$result
[1] TRUE
```

Maybe a context is not restored properly?

**Comment by programLyrique** [comment] 2021-12-19 12:05
I get the same error with the following files:

```
rtrim/vignettes/rtrim_confidence_intervals.R
Rraven/vignettes/Rraven.R
opera/vignettes/regional_forecasting.R
rtrim/vignettes/rtrim_for_TRIM_users.R
rtrim/vignettes/Skylark_example.R
rtrim/vignettes/taming_overdispersion.R
NegBinBetaBinreg/examples/NegBinBetaBinreg.Rd.R
rtrim/vignettes/rtrim_2_extensions.R
```

**Comment by fikovnik** [comment] 2022-01-17 15:16
Should be fixed except for:

```
[1] "Rraven/vignettes/Rraven.R"
```

This one is missing a file:

```
Error in warbleR::check_sels(X, path = path, wav.size = TRUE, pb = pb,  :
  no .wav files found
```

and

```
[2] "rtrim/vignettes/rtrim_2_extensions.R"
```

Again, the problem is a missing file. This time, it tries to load a file which is present in the `vignettes` source package directory, but not in the installed package.

**Closed as completed by fikovnik** 2022-01-17 15:16 UTC
